server:
  port: 7900
  
spring:
  application:
    name: zh-cart-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
            
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

mybatis:
  mapUnderscoreToCamelCase: true
  typeAliasesPackage: cn.zh.pojo
  mapperLocations: classpath:mappers/*.xml
  
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

ribbon:
  eureka:
    enabled: true
    
logging:
  level: 
    cn.zh.mapper: debug
